### ISSUE TITLE
selecting a course for the activity

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#10]
![image](https://github.com/KUJP-code/materials/assets/161788348/55840197-5a7f-40e2-88af-e885bff8dff6)

since the admin will do this, can you move this part to the top  like this 
![image](https://github.com/KUJP-code/materials/assets/161788348/2e420020-b6e9-46ce-8bfe-346931f82e54)

**Comment by Brett-Tanner** [comment]
Didn't get around to it yet but I was just not going to show those fields for non-admins. Sound good to you?

**Comment by Brett-Tanner** [comment]
Ok, on top for admins and hidden for non-admins

**Comment by Brett-Tanner** [comment]
Closed by 20fcf8ae023ead34ef2853a552821e8dca6f283f
