### ISSUE TITLE
text boxes

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#11]
![image](https://github.com/KUJP-code/materials/assets/161788348/9f740ac9-23ce-4b44-9ed3-72ddf7b41ce7)
we can only expand the text boxes vertically, it makes it very difficult to see and write, could you either make them wide from the start or let them expand horizontally too

**Comment by Brett-Tanner** [comment]
Ah that's super weird hahaha, hadn't looked at form styling at all other than making it superficially pretty. It's an easy change. How many lines would be good initially? (horizontally)

**Comment by LuissForce** [comment]
i would say all except instructions 4, instructions (activity) should have  10

**Comment by Brett-Tanner** [comment]
Cool cool
