### ISSUE TITLE
Activity control 

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#13]
![image](https://github.com/KUJP-code/materials/assets/161788348/29138a92-a836-42b1-b200-4952d29f5cf7)

Can we have a list of activities and when were they used, this will help plan for future courses, frequently used , and inactive activities

**Comment by Brett-Tanner** [comment]
As discussed this is possible, but the x-axis would likely be course names rather than years as it makes more sense in this context. Courses might be used over many different years at different schools

**Comment by Brett-Tanner** [comment]
![Screenshot 2024-05-24 121039](https://github.com/KUJP-code/materials/assets/100023145/8b0a7ea7-b19a-4026-bd57-41eec7ba5332)

Like this? (Obviously with better formatting)

**Comment by Brett-Tanner** [comment]
![Screenshot 2024-05-24 122021](https://github.com/KUJP-code/materials/assets/100023145/e1b435a1-2997-400e-9a9a-40ad3a57d77e)

Updated with some more distinction between rows and course/lesson combos that are used highlighted green
