### ISSUE TITLE
Review subtitle

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#17]
same here , add a new textbox
![image](https://github.com/KUJP-code/materials/assets/161788348/e77ab57b-83c0-4a4e-b9f9-3c9183f1ce1b)

Add it here  (Between large groups and outro)
![image](https://github.com/KUJP-code/materials/assets/161788348/c501dd2d-000d-4f27-9821-ba4b6711bc7e)

**Comment by Brett-Tanner** [comment]
As per my previous replies. This one could have been a single issue, it's the same thing but just in different places. So I'll close as a duplicate and just leave the one I wrote a big reply for.
