### ISSUE TITLE
Active students

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#19]
this app will not be connected to the  SS right? 
if not then, how about either on the student profile or  the student page adding an active/inactive student selection option 
![image](https://github.com/KUJP-code/materials/assets/161788348/27047ee2-3ba7-44c7-983b-aa3c4c64618e)

**Comment by Brett-Tanner** [comment]
I don't see the connection between those two things

**Comment by LuissForce** [comment]
in the SS SMs change the student info, whenever they quit, so they can be filtered out 
As an admin, I think they want to see only active students' information

**Comment by Brett-Tanner** [comment]
Ah yeah I knew about that. Curriculum can't see students to begin with, and admins want to be able to see their data even if they're inactive until we have to to delete it. Event site doesn't track this either and it's never been an issue, so not planning to add this.
