### ISSUE TITLE
Image format info

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#25]
![image](https://github.com/KUJP-code/materials/assets/161788348/843d0fc3-696b-47d7-85d2-94fab589a5d6)
over here it says format PDF, instead of Jpg or png (I uploaded jpg and worked, tried PDF and it didn't work)

**Comment by Brett-Tanner** [comment]
This is where you upload the image for the PDF, so it correctly stopped you uploading a PDF.

**Comment by LuissForce** [comment]
yes, it did, but could you change the term to jpeg or png, it might confuse other teachers trying to upload a pdf file instead haha
