### ISSUE TITLE
Uploaded resource 

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#26]
![image](https://github.com/KUJP-code/materials/assets/161788348/8649b727-c0ca-4a8a-aee3-1f94b8046bad)

![image](https://github.com/KUJP-code/materials/assets/161788348/b0668a80-ee2c-4fb5-8845-0146def0a465)

I can't tell if a file was correctly uploaded, and I can't find it here.
Can we add the list of uploaded resources, and the option to delete them

**Comment by Brett-Tanner** [comment]
Yep, will get around to it at some point
