### ISSUE TITLE
Image outline

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#30]
![image](https://github.com/KUJP-code/materials/assets/161788348/72b408d0-f624-432e-b920-db81c29cfb19)

Is there a way to "crop" or mask the corners of the uploaded picture?
or what do you think is better?

**Comment by Brett-Tanner** [comment]
Will look into it, how easy would it be on the curriculum team's end?

**Comment by LuissForce** [comment]
I think difficult not everyone has access to for example illustrator.
is it possible to put the activity picture under the activity template, and make that area transparent on the template, that way it will "automatically" crop the picture

**Comment by Brett-Tanner** [comment]
[Possible solution](https://github.com/janko/image_processing/blob/master/doc/vips.md#composite), make a composite of the uploaded image with a mask of the box it's meant to fit in. Mask will go over the top of the image and cut off the corners

**Comment by Brett-Tanner** [comment]
No easy way to do this automatically, curriculum can round the edges themselves.
