### ISSUE TITLE
Update date of activities

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#32]
![image](https://github.com/KUJP-code/materials/assets/161788348/eaccbfce-018d-4c9f-9219-7ee13188787a)

Changing the date, and clicking on update date doesn't work, nothing happens after I click on the change date button

**Comment by Brett-Tanner** [comment]
https://github.com/KUJP-code/materials/assets/100023145/29dbd62f-9a90-4ea7-b4be-868465a82c6a

Works fine for me, middle one seems to error but the change does still go through

**Comment by LuissForce** [comment]
I see changing the week doesn't work
if I try week and day at the same time neither work
it only works changing the day

**Comment by Brett-Tanner** [comment]
https://github.com/KUJP-code/materials/assets/100023145/84760022-13ed-4b96-844b-38be6e59448c

Are you absolutely sure they're not working? I can change both the week and day multiple times with no issues. Maybe the one you were working on just moved to a different spot since they're not sorted at all yet?

**Comment by Brett-Tanner** [comment]
Maybe share a screen recording of it not working for you?

**Comment by LuissForce** [comment]
see
https://github.com/KUJP-code/materials/assets/161788348/062474a2-29b1-482e-9719-1c8fdcc99686

**Comment by LuissForce** [comment]
see
https://github.com/KUJP-code/materials/assets/161788348/ad0dd3f5-bab4-4e06-b93b-8f5955e8f523

**Comment by Brett-Tanner** [comment]
Changing Sea Animals to 4/F results in a server error when I try it but change still goes through. Changing another activity to 4/F does not trigger a server error
