### ISSUE TITLE
Prevent duplicate lessons

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#34]
![image](https://github.com/KUJP-code/materials/assets/161788348/c5f3206f-1456-486a-b4fa-7e9cd5f9ab8e)

Can we have an activity warning or something to prevent duplicated activities in the system if these fields are the same: 
title, level,  and subtype

**Comment by Brett-Tanner** [comment]
This is difficult because not everything has a subtype, so you can't really use it in validations. Is unique names within a level fine?

**Comment by LuissForce** [comment]
Yes , then levels and names works fine
