### ISSUE TITLE
Language error

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#35]
![image](https://github.com/KUJP-code/materials/assets/161788348/9bf31d57-febc-4b42-a012-33edc112f9fc)

I was filing up an activity, I clicked on the language icon, and sent me this error, then I had to go back and lost all the progress haha

![image](https://github.com/KUJP-code/materials/assets/161788348/6002555a-860f-482b-8bc6-7a0507350571)

**Comment by Brett-Tanner** [comment]
Losing all progress is expected, changing language reloads the page. The error lead me to something interesting though, so thanks.
