### ISSUE TITLE
Filters /sorting

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#36]
![image](https://github.com/KUJP-code/materials/assets/161788348/0c9baf29-cb24-48fe-b351-4c8fc5c4e9cf)

Can you add the option to filter and sort by week, by type of activity in this section
that way we can tell what day of what weeks have and don't have an activity assigned

**Comment by Brett-Tanner** [comment]
They're already sorted into type of activity (DA, English, Phonics etc.). They'll be sorted within that by week then day in the next release.
