### ISSUE TITLE
Edit activity

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#4]
![2](https://github.com/KUJP-code/materials/assets/161788348/c52a30a8-0ac5-4d88-8f94-c2d5abe17686)

When I click on edit the activity, and I don't change anything but click save, it shows everything as new changes

It's so hard to visualize the activity when filling the small squares, I will work on a wireframe, design how it could help visually, and share it with you asap.

**Comment by LuissForce** [comment]
maybe we could add the info, with the actual activity layout png

**Comment by Brett-Tanner** [comment]
> maybe we could add the info, with the actual activity layout png

That's doable, though it does double the work I need to do every time we change the layout of the template. I'd have to modify the template code, then also the styles for the relevant form.

Also, wouldn't work for proposed changes at all in the current implementation as their form is autogenerated.

**Comment by Brett-Tanner** [comment]
Just realised green is actually the color for unchanged fields. Do you think it would be better to just exclude unchanged fields? Changes are in red.

**Comment by LuissForce** [comment]
yes, remove the unchanged, and if possible show a comparative old - new of that section.

**Comment by Brett-Tanner** [comment]
Resolved by new comparison layout/flow
