### ISSUE TITLE
Edit Activity resources list

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#44]
on  the list of resources we have uploaded to each activity, could you add the option to delete the file or  update it (substitute) 
![image](https://github.com/KUJP-code/materials/assets/161788348/21a6ecb1-5e32-4760-93d8-06ddc189bba2)

**Comment by Brett-Tanner** [comment]
Ah, didn't see that you wanted a button to delete them last time. Will add that with a confirmation popup to actually delete them

**Comment by LuissForce** [comment]
Yes, thank you
I noticed today that if I upload a new resource it replaces the file, but like that, now I found the issue that I can't upload more than 1 resource to an activity.
