### ISSUE TITLE
Kindy/Keep up/ Specialist Class

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#47]
Can you add Kindy English class and phonics above LAND
![image](https://github.com/KUJP-code/materials/assets/161788348/f2299176-12f6-4495-acfa-1d5fbd8ee52e)

For Keep up and Specialist , What do you think?  Where would be better to position them?

**Comment by Brett-Tanner** [comment]
![Screenshot 2024-06-03 173547](https://github.com/KUJP-code/materials/assets/100023145/c40bb3b8-f500-4363-b87c-b51f8608f652)

Keep Up and Specialist are just below right now, like ^this

**Comment by LuissForce** [comment]
nice thanks
