### ISSUE TITLE
Elementary only level (no kindy)

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#53]
Can you add the all Elementary levels only (that includes Land1 to Specialist) that excludes kindy
There is "all levels" but It includes kindy

![image](https://github.com/KUJP-code/materials/assets/161788348/14e2512a-dd96-4fea-be6d-da54ee670156)

**Comment by Brett-Tanner** [comment]
Can you explain the purpose of this? Like what do you want as an outcome from adding it?

**Comment by LuissForce** [comment]
to exclude Kindy from special activities like level check

**Comment by Brett-Tanner** [comment]
Just select a random elementary level instead for lessons where the specific level doesn't matter, the sorting can be handled from that
