### ISSUE TITLE
Exercise Kindy vs ELE

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#57]
![image](https://github.com/KUJP-code/materials/assets/161788348/ed9f86cb-19ac-447f-b597-452a7846bab5)

right now and for a long time , the exercise guides are for ele and for kindy , but Kindy and ELE do different exercise in the same day.

so instead of duplicating the activity guides, can we select the level every time we add that guide to a new course (a new day), something like that.
this is so we don't have to upload the same guides twice but with a different level.
![image](https://github.com/KUJP-code/materials/assets/161788348/31615431-9b73-4bae-8773-7edc1b9e1fe2)

For example this guide is for ELE on Monday
but I want this guide (activity) to be only for kindy on Wednesday 
![image](https://github.com/KUJP-code/materials/assets/161788348/953e8f08-b3b9-4d3e-a2c8-1c7e823aae4d)

**Comment by Brett-Tanner** [comment]
Not planned, adds a decent amount of complexity/an extra column to a heavily used DB table for the benefit of saving a single lesson creation per Exercise lesson. Could potentially look into adding a 'Copy as Kindy' button but slippery slope.
