### ISSUE TITLE
student repeated

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#58]
![image](https://github.com/KUJP-code/materials/assets/161788348/c9c60825-a8ea-4afa-9664-ce0d4c166b44)

In the student's list for galaxy in Mitaka for some reason, there are two Sara Amari, the first one in the list works fine, but when I click on the 2nd one in the list it sends me to the error page.
![image](https://github.com/KUJP-code/materials/assets/161788348/3e2fab3d-b6f0-432c-b646-a0c92d6819ad)

This student is only in 1 class, so the class is not duplicated.
![image](https://github.com/KUJP-code/materials/assets/161788348/7f267772-d78f-46b9-9b48-7d909e8e5f43)

**Comment by Brett-Tanner** [comment]
Was a leftover test student, deleted.
