### ISSUE TITLE
Brush up activities 

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#59]
![image](https://github.com/KUJP-code/materials/assets/161788348/62cc0e3f-70d5-4b22-ba95-2fbf314be1be)
The brush up activities don't show up in a teacher account (the first screenshot is from the admin account, the second one is from a teachers account)
![image](https://github.com/KUJP-code/materials/assets/161788348/fdb061bc-1314-4c45-89e6-df00824a9341)

**Comment by Brett-Tanner** [comment]
Ah, they have to be part of a course, and there's currently no way to add them to a course through the UI. Will add that for Thursday.
