### ISSUE TITLE
Exercise activity

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#6]
the exercise  filter doesn't work.
 Can you add to the filters the subcategories too, ELE arts and crafts, ELE Discovery...
![5 1](https://github.com/KUJP-code/materials/assets/161788348/d73209b9-0f41-442d-8521-d5aa80f097bb)
![5](https://github.com/KUJP-code/materials/assets/161788348/ebdc492c-a2d3-46aa-84d0-e94ec12d4f0a)

**Comment by Brett-Tanner** [comment]
Ah yeah that's cos I forgot to perform an authorization check for that lesson type's index action, and I set it to throw errors when authorization isn't performed. It's fixed on my local copy, and will be on live next time I push a new version.
