### ISSUE TITLE
monthly materials 

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#65]
since teachers don't know the number of the week, I think it would be easier if they could select the date instead of the number of weeks
From-to
![image](https://github.com/user-attachments/assets/be5afdee-e95a-4f75-89b0-0f9c97231a49)
![image](https://github.com/user-attachments/assets/fffba436-4219-4ea4-95df-75cfb1c13eb5)

what do you think?

**Comment by Brett-Tanner** [comment]
![Untitled](https://github.com/user-attachments/assets/701ec958-6ff6-4bda-aa51-6231c0a45de6)

**Comment by LuissForce** [comment]
yes it shows the date, but first they have to start guessing until they get the correct date ... then the next month they will have to guess again...
