### ISSUE TITLE
Lesson sorting and filtering 

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#85]
This is for the backend, we have several filters, but we noticed we need a few more to improve the checking and organization, 
![image](https://github.com/user-attachments/assets/26eece82-9d64-4993-9769-5c8ed663cafd)

Can you add the option to filter /  sort by creation day?

Also,  add a last checked date, maybe like a checkbox, then the curriculum member can check and it records the date and the member that checked it, so we can then filter by that date.

Can you add a filter by week? I guess this will also have to do with the organization.

for example, i want to filter in the Kids Up course the week 35, and see the list of all the activities assigned to that week.

the week filter could also work here if that makes it easier 
![image](https://github.com/user-attachments/assets/70ae9c46-db4c-4011-a053-c989e4ae7beb)

**Comment by JaysonPye** [comment]
I will start by adding week searching functionality and go from there, I am hoping to get to this next week, we can talk about adding checks and stuff afterwards.
