### ISSUE TITLE
Submitting an activity

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#9]
![image](https://github.com/KUJP-code/materials/assets/161788348/4551ab69-9134-45ad-b047-ebbc46baf8b6)

The new activity guide format is almost done, although still needs some visual work, we already have the fields we need to input when uploading the guides. 
can you make the boxes for these items and in this order:

1. Subtype
2. Title
3. Goal / Description
4. Level
5. Land Language goals
6. Sky Language goals
7. Galaxy Language goals
8. You will need (materials)
9. Introduction (warm-up)
10. Did you know? (an interesting fact about the topic)
11. Activity (Instructions)
12. Large group ideas
13. Review (Examples)
14. Resources (upload)
15. Notes (internal only)
16. Links

**Comment by Brett-Tanner** [comment]
Is this for the Daily Activities? Exercise?

**Comment by Brett-Tanner** [comment]
> Is this for the Daily Activities? Exercise?

Luis told me it's for DailyActivities
